services:
  frontend:
    build: ./TrackSite
    restart: always
    networks:
      - race-net
  reverse-proxy:
    image: nginx:stable-alpine
    container_name: raceapi-reverse-proxy
    restart: always
    volumes:
      - ./nginx-reverse.conf:/etc/nginx/conf.d/default.conf
    networks:
      - race-net
networks:
  race-net:
    driver: bridge
